### ISSUE TITLE
The tool only runs in Firefox

### ISSUE THREAD

**Issue by eckes** [JoernMueller/Ice-Ed#2]
`String.prototype.replaceAll` is not available on Chrome yet...

See https://github.com/JoernMueller/Ice-Ed/pull/1

**Comment by JoernMueller** [comment]
Thank you very much for your feedback and contribution. They are a very valueable input for me.
I already did a workaround for the `replaceAll` issue in my local development branch, but as your approach is of better quality I will swap to this solution.

**Comment by eckes** [comment]
Closing, fixed with #1
